name: Annual F1 Event Schedule

on:
  schedule:
    # Run on January 1st at 00:00 UTC (before F1 season starts)
    - cron: '0 0 1 1 *'
  workflow_dispatch:  # Allow manual triggering

# Add permissions for GitHub Actions to push to repository
permissions:
  contents: write

jobs:
  fetch-event-schedule:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create cache directory
      run: mkdir -p .cache/event_schedule
      
    - name: Create data directory
      run: mkdir -p data
      
    - name: Fetch F1 event schedule
      run: python src/data_prep/get_event_schedule.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/sessions_*.csv
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update F1 event schedule for $(date +%Y)"
          git push
        fi
